name: Build for MIPS/MIPSEL

on:
  push:
    tags: [ "v*" ] # 当推送以 v 开头的标签时触发发布
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          # 小端序：大多数联发科路由器
          - arch: mipsel_24kc
            sdk_path: releases/23.05.0/targets/ramips/mt7621
          
          # 大端序：大多数高通/阿瑟罗路由器
          - arch: mips_24kc
            sdk_path: releases/23.05.0/targets/ath79/generic

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Build with OpenWrt SDK
        uses: gh-action-community/openwrt-sdk-action@v2
        env:
          ARCH: ${{ matrix.arch }}
          SDK_URL_PATH: ${{ matrix.sdk_path }} # 引用上面定义的路径
          FEEDNAME: custom_feeds
          PACKAGES: iptv_scanner
          NO_SIGNCHECK: true

      - name: Upload IPK
        uses: actions/upload-artifact@v4
        with:
          name: iptv_scanner-${{ matrix.arch }}
          path: bin/packages/${{ matrix.arch }}/custom_feeds/*.ipk
